# Generated by Django 5.2.5 on 2025-08-29 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_foto', models.DateField(default=django.utils.timezone.now)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('status', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('RASCUNHO', 'Rascunho')], default='RASCUNHO', max_length=10)),
                ('estrela', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_foto'],
            },
        ),
    ]
